apiVersion: v1
kind: Pod
metadata:
  name: flag4
  labels:
    app: flag4
spec:
  containers:
  - name: flag4
    image: gitea/gitea:1.5.1 
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: hostsvolume
        mountPath: /flag4
    ports:
    - containerPort: 80
    securityContext:
      privileged: true
  volumes:
  - name: hostsvolume
    hostPath:
      path: /
